
license= "MIT"
release="main"

[sign]
keyId=""
password=""
secretKeyRingFile=""

[center]
username = ""
password = ""

[[authors]]
id = "baka4n"
name = "baka4n"
url = "https://github.com/baka4n"

[[authors]]
id = "dove-home-team"
name = "Dove Home Team"
url = "https://github.com/dove-home-team"
